# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 23:29
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180206_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auther_email',
            field=models.CharField(blank=True, max_length=240, null=True, validators=[blog.models.validate_author_email]),
        ),
    ]
