# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 23:57
from __future__ import unicode_literals

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180206_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auther_email',
        ),
        migrations.AddField(
            model_name='post',
            name='author_email',
            field=models.EmailField(blank=True, max_length=240, null=True, validators=[blog.validators.validate_author_email, blog.validators.validate_algo]),
        ),
    ]
